# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171116_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='skin',
            field=models.ImageField(blank=True, upload_to='profiles_skin/', verbose_name='Foto de capa'),
        ),
    ]
