# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20171116_1445'),
        ('core', '0005_configuration_skin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título do anúncio')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Atalho para o anúncio')),
                ('short_description', models.CharField(blank=True, max_length=255, verbose_name='Breve descrição')),
                ('body', models.TextField(verbose_name='Descrição do anúncio')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Preço do anúncio')),
                ('status', models.BooleanField(choices=[(True, 'Ativado'), (False, 'Desativado')], default=False, verbose_name='Status do anúncio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category', verbose_name='Categoria')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile', verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Anúncio',
                'verbose_name_plural': 'Anúncios',
            },
        ),
    ]
