# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20171116_1445'),
        ('core', '0006_ad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='provider',
        ),
        migrations.AddField(
            model_name='ad',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile', verbose_name='Usuário'),
            preserve_default=False,
        ),
    ]
