# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 20:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_auto_20171124_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Título do anúncio')),
                ('slug', models.SlugField(unique=True, verbose_name='Atalho para o anúncio')),
                ('description', models.TextField(verbose_name='Descrição do anúncio')),
                ('skills', models.CharField(blank=True, max_length=255, null=True, verbose_name='Experiências')),
                ('curriculum', models.TextField(blank=True, null=True, verbose_name='Curriculum Vitae')),
                ('video', models.CharField(blank=True, max_length=500, null=True, verbose_name='Seu vídeo de apresentação')),
                ('main_address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Seu endereço principal')),
                ('budget_is_paid', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], verbose_name='Orçamento é pago?')),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Preço base de seu trabalho')),
                ('price_shit', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Valor de deslocamento')),
                ('price_detail', models.CharField(blank=True, max_length=255, null=True, verbose_name='Detalhe suas tarifas')),
                ('budget_free', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], verbose_name='Orçamento Grátis?')),
                ('picture', models.ImageField(upload_to='professional_picture/', verbose_name='Foto')),
                ('skin', models.ImageField(blank=True, upload_to='professional_skins/', verbose_name='Skin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category', verbose_name='Segmento de atuação')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users_professional', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profissional',
                'verbose_name_plural': 'Profissionais',
            },
        ),
    ]
