# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_professional'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='status',
            field=models.BooleanField(choices=[(True, 'Publicado'), (False, 'Em análise')], default=False, verbose_name='Situação'),
        ),
    ]
