# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='Primeiro Nome')),
                ('last_name', models.CharField(max_length=200, verbose_name='Sobrenome')),
                ('cellphone', models.CharField(max_length=15, verbose_name='Telefone/Celular')),
                ('whatsapp', models.CharField(max_length=15, verbose_name='Whatsapp')),
                ('email', models.CharField(blank=True, max_length=255, verbose_name='Email')),
                ('facebook', models.CharField(blank=True, max_length=500, verbose_name='Página / Perfil Facebook')),
                ('city_state', models.CharField(max_length=255, verbose_name='Cidade / Estado')),
                ('segment', models.CharField(max_length=255, verbose_name='Segmento de Negócio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Leads',
            },
        ),
    ]
