# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='suggestion',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Sugestão'),
            preserve_default=False,
        ),
    ]
