# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0003_auto_20171107_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Email'),
        ),
    ]
