# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 18:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_email_confirmation.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
            ],
            options={
                'abstract': False,
            },
            bases=(simple_email_confirmation.models.SimpleEmailConfirmationUserMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='documents_profiles/', verbose_name='Foto do documento')),
                ('selfie_document', models.ImageField(upload_to='selfies_documents/', verbose_name='Selfie com o documento')),
                ('status', models.BooleanField(choices=[(True, 'Verificado'), (False, 'Não verificado')], default=False, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='profile_users/', verbose_name='Avatar')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Bio')),
                ('location', models.CharField(blank=True, max_length=30, verbose_name='Localização')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('gender', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outros', 'Outros')], max_length=100, null=True, verbose_name='Eu sou')),
                ('cpf', models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='Whatsapp')),
                ('telegram', models.CharField(blank=True, max_length=2, null=True, verbose_name='Telegram')),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('country', models.CharField(blank=True, default='Brasil', max_length=20, null=True, verbose_name='País')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cidade')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Endereço')),
                ('address_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('address_remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='Complemento')),
                ('townhouse', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bairro')),
                ('provider', models.BooleanField(choices=[(True, 'Sou prestador de serviços'), (False, 'Não presto serviços')], default=False, verbose_name='Prestador de serviço?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
    ]
