# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=250, verbose_name='Primeiro Nome'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=250, verbose_name='Sobrenome'),
        ),
    ]
