# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20171102_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Link do seu perfil ou página'),
        ),
    ]
