# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_facebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skin',
            field=models.ImageField(blank=True, upload_to='profile_skin/', verbose_name='Skin'),
        ),
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Apelido'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to='profile_avatar/', verbose_name='Avatar'),
        ),
    ]
