# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20171116_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='professional',
            field=models.BooleanField(choices=[(True, 'Sou um profissional'), (False, 'Não sou um profissional')], default=False, verbose_name='É profissional?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='provider',
            field=models.BooleanField(choices=[(True, 'Sou um profissional'), (False, 'Não sou um profissional')], default=False, verbose_name='Prestador de serviço?'),
        ),
    ]
