# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20171103_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Apelido'),
        ),
    ]
