# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20171124_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='provider',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Prestador de serviço?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='professional',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='É profissional?'),
        ),
    ]
